fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.3.2
    lvm: git://github.com/puppetlabs/puppetlabs-lvm.git
    mysql: git://github.com/puppetlabs/puppetlabs-mysql.git
  symlinks:
    site_mysql: "#{source_dir}"
